config/routes.rb
CalendarAPI::Application.routes.draw do

  
  match 'createEvent' => 'home#generate', :as => 'generate'
  match 'cal/popup' => 'calendar#popup', :as => 'popup'
  match 'cal/embed' => 'calendar#embed', :as => 'embed'
  match 'cal/to/google' => 'calendar#googlecalendar', :as => 'googlecalendar'
  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def get_params
    opts = {
      :sy => params[:sy],
      :sm => params[:sm],
    }
    
    [:sd, :st, :sz, :ey, :em, :ed, :et, :ez].each do |k|
      next if [:sz, :ez].include?(k) && !(params[k] =~ /[+-]\d{2}:\d{2}/)
      if params[k]
        opts[k] = params[k]
      end
    end
    
    # default title
    opts[:tt] = params[:tt] || "My Event"
    
    opts
  end
end

app/controllers/calendar_controller.rb
class CalendarController < ApplicationController
  # create embed => embed => popup
  
  def popup
    opts = get_params 

    @title = opts[:tt]
    @url = googlecalendar_url opts
    @datestring = Time.new(opts[:sy],opts[:sm], opts[:sd]).strftime("%A, %B %d, %Y ")
    
    @datestring = params[:st] + ", "+ @datestring if params[:st]
      
    
    render layout: false
  end
  
  def embed 
    opts = get_params
    @url = popup_url(opts)
  end
  
  # http://www.google.com/googlecalendar/event_publisher_guide_detail.html
  def googlecalendar
    sy = params[:sy].to_i
    sm = params[:sm].to_i
    sd = params[:sd]
    st = params[:st]
    sz = params[:sz] =~ /[+-]\d{2}:\d{2}/ ? params[:sz] : (Time.now.strftime("%z")[0..2] +":"+Time.now.strftime("%z")[3..4])
    
    ey = params[:ey]
    em = params[:em]
    ed = params[:ed]
    et = params[:et]
    ez = params[:ez]
    
    
    # e.g. 20060415T180000Z
    if !st.blank? && st =~ /\d{0,2}[:.]\d{2}/
      sta = st.scan /\d+/
      sth = sta.first.to_i + (st.include?('p') ? 12 : 0)
      stm = sta.last.to_i
      
      # timezones are kinda messed up when crossing dst
      date = Time.new(sy, sm, sd, sth, stm, nil, sz).getutc.strftime('%Y%m%dT%H%M%SZ')
    else
      date = Time.new(sy, sm, sd, nil, nil, nil, sz).getutc.strftime('%Y%m%d')
    end

    # if !ey.blank?
      # date += "/#{Time.now.getutc.strftime('%Y%m%d')}"
    # else
      date += "/#{date}"
    # end
    
    options = {
      action:  'TEMPLATE',
      text:    params[:tt] || "New Event",
      dates:   date
    }
    
    opt = options.collect {|k,v| "#{CGI.escape k.to_s}=#{CGI.escape v}"}.join '&'
    # render :text => options.inspect and return
    redirect_to "http://www.google.com/calendar/event?" + opt
  end

  private
  # reads params into a hash


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    current_time = Time.new();
    @current_year = current_time.year
  end

  def generate
    sy = params[:start_year] || Time.now.year
    sm = params[:start_month] || Time.now.month
    sd = params[:start_day] || Time.now.day
    st = params[:start_time]
    sz = params[:sz] if params[:sz] =~ /[+-]\d{2}:\d{2}/

    ey = params[:ey]
    em = params[:em]
    ed = params[:ed]
    et = params[:et]
    ez = params[:ez]

    @opts = {
      :sy => sy,
      :sm => sm,
      :sd => sd,
      :st => st,
      :sz => sz,
      :ey => params[:ey],
      :em => params[:em],
      :ed => params[:ed],
      :et => params[:et],
      :ez => params[:ez],
      :tt => params[:event_name] || "My Event"
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/calendar_helper.rb
module CalendarHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/calendar/embed.js.erb
<%
the_id = "capi_#{(Time.now.to_i*rand).to_i}"
style = "display: inline-block; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; text-decoration: none; color: #333; font-size: 12px;  margin: 5px; padding: 5px; font-weight: 500;"
script = "window.open(this.href,'capi_add','height=300,width=400,scrollbars=no,resizable=no');return false;"
%>

document.write("<a class='button' href='<%= @url %>' style=\"<%= style %>\" target='_blank' onclick=\"<%= script %>\" id='<%= the_id %>'>+ <img style='display: inline-block; margin: 0 5px; position: relative; top: 1px' src='<%= root_url %>/images/cal.png' />Add To Calendar</a>");

<% if false %>
// http://drnicwilliams.com/2006/11/21/diy-widgets/
(function() {
  document.getElementById('<%= the_id %>').onclick = function() {
    alert('CLICKED');
  };
  
  function requestContent() {
    var script = document.createElement('script');
    script.src = "";
    document.getElementsByTagName('head')[0].appendChild(script)
  }

  this.serverResponse = function( data ) {
    if (!data || !data['files'][0]) return;
    
    // if target not passed
    var dest = data['target'] ? data['target'] : "<%= the_id %>"
    var div = document.getElementById(dest);
    var toc = data['files']
    
    var theContents = "<style type='text/css'>.pancake_link_date { display: inline-block; width: 100px; }</style>";
    for (var i=0;i< toc.length;i++) {
      theContents += "<div class='pancake_link'>";
      if (toc[i].length == 3)
        theContents += "<span class='pancake_link_date'>" + toc[i][2] + "</span>";
      theContents += "<a class='title' href='" + toc[i][1] + "'>"+toc[i][0] + "</a></div>";
    }
    div.innerHTML = theContents;
    div.style.display = 'block';
  }
  
  // requestContent();
  return this;
})();
<% end %>

app/views/calendar/popup.html.erb
<html>
  <head>
    <%= stylesheet_link_tag    "application", :media => "all" %>
  </head>
  <body id='x-calendar-popup'>
    <div id='popup_container'>
      <div id='popup_header'>
        Add to my calendar
      </div>
      <div id='popup_body'>
        <div id='popup_top'>
          <div id='popup_title'><%= @title %></div>
          <div id='popup_subtitle'><%= @datestring %></div>
        </div>
        <a href='<%= @url %>' target='_blank' class='popup_place'>
          <img src='/images/google_calendar.png'>
        </a>
        <a href='<%= @url %>' target='_blank' class='popup_place'>
          <img src='/images/icallogo.png'>
        </a>
      </div>
    </div>
  </body>
</html>

app/views/home/generate.html.erb
<h2>Copy this code!</h2>
<% s = "<script src='#{embed_url @opts}'></script>" %>
<div>
  <%== s %>
</div><br />
<div>
<textarea style='height: 100px' "share_link" id='sharelink' readonly>
<%= s%>
  </textarea></div>

app/views/home/index.html.erb
<p style='border-bottom: 2px solid #aaa; padding-bottom: 40px; margin-bottom: 30px'>The Calendar API allows you to create easy to use buttons for people to add things to their calendar</p>

<div style='float:right; padding: 10px; background: #fafafa'>
<p style='margin: 0'>Example:</p>
<div><script src='/cal/embed?sd=4&sm=10&st=5%3A00pm&sy=2014&tt=CalendarAPI+Event'></script>
</div>

</div>
<%= form_tag("/createEvent", :method => "get") do %>
  <div id="event_header">

    <div id="event_name">
        <h2><%= label_tag(:event_name, "Event Name"); %></h2>
      <div class="field">
        <%= text_field_tag(:event_name, '', :placeholder =>'My Excellent Event') %> <br />
      </div>
    </div>

<!--     <div id="event_description">
      <div class="label">
        <%= label_tag(:event_description, "Event description"); %>
      </div>
      <div class="field">
        <%= text_field_tag(:event_description) %> <br />
      </div>
    </div> -->

  </div>

  <div id="event_start">
    <h2>Event Detail</h2>

    <div class="field">
      <%= text_field_tag(:start_time, '', :placeholder => 'time') %> <br />
    </div>

    <div class="field" style='width: 200px'>
      <%= select_tag :start_month, options_for_select(1.upto(12).collect {|i| [Date::MONTHNAMES[i], i]}) %>
      <%= text_field_tag(:start_day, '', :placeholder => 'day', :style => 'width: 80px; float: right') %> 
    </div>

    <div class="field">
      <%= text_field_tag(:start_year, @current_year, :placeholder => 'year') %> <br />
    </div>
  </div>
  <!-- 
    <div id="event_end">
      <h2>Event end</h2>

      <div class="field">
        <%= text_field_tag(:end_time, '', :placeholder => 'time') %> <br />
      </div>

      <div class="field">
        <%= text_field_tag(:end_month, '', :placeholder => 'month') %>
      </div>

      <div class="field">
        <%= text_field_tag(:end_day, '', :placeholder => 'day') %> 
      </div>

      <div class="field">
        <%= text_field_tag(:end_year, @current_year, :placeholder => 'year') %> <br />
      </div>
    </div> -->
  
    <div style='clear: both' class="submit"> 
      <%= submit_tag("Create Event!"); %> <br />
    </div>
<% end %>



<!--
Form

Event Name
Start time
  time, month, day, year
End time
  time, month, day, year
  Description

--!>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalendarAPI</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= "x-#{params[:controller]}-#{params[:action]}" %>'>
  <div id='header'>Calendar API</div>
<div id='container'>
<%= yield %>
</div>
</body>
</html>